version: '2'

services:
  app:
    image: vsokoltsov/interview360
    command: bash -c "python3 app/manage.py migrate && cd app && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    mem_limit: 262144000
    ports:
      - "80:8000"
    env_file: ./.env.prod
    links:
      - kibana
