version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            touch .env
            echo "DOCKER_ENV='true'" >> .env
            echo "S3_KEY=$S3_KEY" >> .env
            echo "S3_BUCKET=$S3_BUCKET" >> .env
            echo "S3_SECRET=$S3_SECRET" >> .env
            echo "ELASTICSEARCH_URL=$ELASTICSEARCH_URL" >> .env
            echo "USER=$USER" >> .env
            echo "HOST=$HOST" >> .env
            echo "PASSWORD=$PASSWORD" >> .env
            echo "TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID" >> .env
            echo "TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN" >> .env
            echo "DEFAULT_CLIENT_HOST=http://localhost:4200" >> .env
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker container prune -f
            docker image prune -f
            docker-compose up -d app db
            docker-compose run app bash -c "cd app && python manage.py test"

      - deploy:
          name: 'Deploy the new image'
          command: |
            pip install fabric3
            docker login -u=$DOCKER_HUB_USER_ID -p=$DOCKER_HUB_PWD
            fab docker_deploy
