version: '3'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: 'interview_manager'
    volumes:
      - /teamcircle/interview360/postgresql/data:/var/lib/postgresql/teamcircle/data
    restart: always
    ports:
      - 5432:5432

  default_app: &default_app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DEFAULT_REQUIREMENTS=development.txt
    volumes:
      - .:/interview360
    env_file: ./.env
    environment:
      - DJANGO_DEFAULT_ENV=development

  interview360:
    <<: *default_app
    image: vsokoltsov/interview360
    container_name: interview360
    command: bash -c "python3 app/manage.py migrate && cd app && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    links:
      - celery_worker
      - celery_beat
    depends_on:
      - db
      - elasticsearch
      - rabbit

  celery_worker:
    <<: *default_app
    container_name: 'celery_worker'
    command: bash -c "cd app && celery -A app.celery worker -l INFO"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    links:
      - rabbit
    depends_on:
      - rabbit

  celery_flower:
    <<: *default_app
    container_name: 'celery_flower'
    command: bash -c "cd app && celery flower -A app.celery"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    ports:
      - '5555:5555'
    links:
      - rabbit
    depends_on:
      - rabbit

  celery_beat:
    <<: *default_app
    container_name: 'celery_beat'
    command: bash -c "cd app && celery -A app beat -l debug"
    links:
      - rabbit
    depends_on:
      - rabbit

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8080:8000"
  #   volumes:
  #     - .:/interview360
  #     - ./deploy/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    links:
      - kibana
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

volumes:
  pg_data: {}
