- name: Copy docker-compose.yml file
  copy:
    src: "{{ default_docker_compose_path }}"
    dest: "{{ server_docker_compose_path }}"

- name: Create folder for nginx config
  file:
    name: "{{ nginx_dir_path }}"
    state: directory

- name: Copy nginx config
  copy:
    src: "{{ default_nginx_app_conf_path }}"
    dest: "{{ nginx_dir_path }}/{{ server_app_config_name }}"

- name: Copy .env file
  copy:
    src: "{{ default_env_file_path }}"
    dest: "{{ home }}/.env"
