filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601
  username: elastic
  password: Altair_69

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: Altair_69
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"