---
- name: install python 2
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)
  become: true

- name: 'install dependencies'
  yum: name="{{ item }}" state=present update_cache=yes
  with_items:
    - 'gcc'
    - 'gcc-c++'
    - 'make'
    - 'git'
    - 'patch'
    - 'openssl-devel'
    - 'zlib-devel'
    - 'readline-devel'
    - 'sqlite-devel'
    - 'bzip2-devel'
    - 'nginx'
    - 'wget'
    - 'curl'

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest
  become: true

- name: Disable selinux
  shell: setenforce 0
  become: true

- name: 'Add 80 port to firewall'
  shell: |
    firewall-cmd --zone=public --add-port=80/tcp --permanent
    systemctl restart firewalld
